name: Database Migration

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
      - '.github/workflows/db-migration.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_HOST: ${{ vars.SUPABASE_DNS }}
      SUPABASE_USER: ${{ vars.SUPABASE_USER }}
      SUPABASE_PORT: 6543
      SUPABASE_PWD : ${{ secrets.SUPABASE_PWD }}
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Echo variables - ${{vars.SUPABASE_DNS}} - ${{env.SUPABASE_USER}}
        env:
          HOST: ${{ vars.SUPABASE_DNS }}
          PWD: ${{ secrets.SUPABASE_PWD }}
        run: echo ok $HOST - $PWD

      - name: Run Flyway Migration
        uses: docker://flyway/flyway:9.22.3
        with:
          args: -configFiles=/github/workspace/flyway.conf migrate
