name: Database Migration

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
      - 'flyway.conf'
      - '.github/workflows/db-migration.yml'

jobs:
  migrate:
    environment: vercel
    runs-on: ubuntu-latest
    env:
      SUPABASE_DNS: ${{ vars.SUPABASE_DNS }}
      SUPABASE_USER: ${{ vars.SUPABASE_USER }}
      SUPABASE_PORT: 6543
      SUPABASE_PWD : ${{ secrets.SUPABASE_PWD }}
    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - run: echo 'Connecting supabase ${{ vars.SUPABASE_DNS }} for user ${{ vars.SUPABASE_USER }}'.

      - name: Run Flyway Migration
        uses: docker://flyway/flyway:11.9.1
        with:
          args: -configFiles=/github/workspace/flyway.conf migrate
